/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.34
</auto-generated>
------------------------------------------------------------------------------ */

using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;

namespace SFU.Mvc.Models
{
	public class MyNewWidgetModel
	{
		public string Message { get; set; }
	}
}