/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.34
</auto-generated>
------------------------------------------------------------------------------ */

using SFU.Mvc.Models;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;

namespace SFU.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "MyNewWidget_MVC", Title = "MyNewWidget", SectionName = "CustomWidgets")]
	public class MyNewWidgetController : Controller, IPersonalizable
	{
		// GET: MyNewWidget
		public ActionResult Index()
		{
			var model = new MyNewWidgetModel();
			model.Message = this.Message;
			return View(model);
		}
		
        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }

		public string Message { get; set; }
	}
}